drinkNames = ["affogato-style frappuccino blended coffee", 
              "affogato-style frappuccino blended creme",
              "americano",
              "americano misto",
              "blended strawberry lemonade",
              "brown sugar oat americano",
              "cappuccino",
              "caramel apple spice",
              "caramel frappuccino",
              "caramel macchiato",
              "caramel ribbon crunch frappuccino",
              "caramel ribbon crunch blended creme",
              "chai creme frappuccino blended creme",
              "chai latte",
              "chocolate creame cold brew",
              "chocolate milk",
              "cinnamon caramel cream cold brew",
              "cinnamon caramel cream nitro cold brew",
              "cinnamon dolce latte",
              "clover brewed coffee",
              "coffee frappuccino blended coffee",
              "starbucks cold brew",
              "cold brew with nondairy vanila cold foam",
              "dragon drink starbucks refresher beverage with oleato golden foam",
              "espresso",
              "espresso con panna",
              "espresso frappuccino blended coffee",
              "espresso machiato",
              "flat white",
              "frozen mango dragonfruit lemonade starbucks refresher",
              "frozen pineapple passionfruit lemonade starbucks refresher",
              "frozen strawberry acai lemonade starbucks refresher",
              "honey almondmilk flat white",
              "honey citrus mint tea",
              "hot brewed tea",
              "hot chocolate",
              "white hot chocolate",
              "iced americano",
              "iced americano with milk",
              "iced brown sugar oat shaken espresso", 
              "iced caramel machiato",
              "iced chai latte",
              "iced chai tea latte with oleato golden foam",
              "iced clover brewed coffee",
              "iced coffee",
              "iced espresso",
              "iced flat white",
              "iced hazelnut oatmilk shaken espresso",
              "iced honey almondmilk flat white",
              "iced latte",
              "iced matcha latte",
              "iced matcha lemonade",
              "iced coffee mocha",
              "iced white chocolate mocha",
              "iced peach green tea",
              "iced peach green tea lemonade",
              "iced shaken espresso",
              "custom iced tea latte",
              "iced toasted vanila oatmilk shaken espresso",
              "java chip frappuccino blended coffee",
              "double chocolaty chip blended creme",   
              "latte",
              "lemonade",
              "london fog latte",
              "mango dragonfruit starbucks refresher",
              "mango dragonfruit lemonade",
              "dragon drink",
              "matche creme frappuccino blended creme",
              "matcha latte",
              "caffe misto",
              "caffe mocha",
              "white chocolate mocha",
              "mocha cookie crumble frappuccino blended coffee",
              "chocolate cookie crumble blended creme",
              "mocha frappuccino blended coffee",
              "white chocolate mocha frappuccino blended coffee",
              "nitro cold brew",
              "nondairy chocolate cold brew",
              "oleato golden foam iced oatmilk shaken espresso",
              "oleato oatmilk latte",
              "paradise drink starbucks refresher beverage with oleato golden foam",
              "pineapple passionfruit starbucks refresher",
              "pineapple passionfruit starbucks lemonade",
              "pineapple passionfruit starbucks paradise drink",
              "royal english breakfast latte",
              "salted caramel cream cold brew",
              "shaken iced black tea",
              "shaken iced black tea lemonade",
              "shaken iced grean tea",
              "shaken iced green tea lemonade",
              "shaken iced passion tango tea",
              "shaken iced passion tango tea lemonade",
              "steamed apple juice",
              "steamed milk",
              "strawberry acai starbucks refresher",
              "strawberry acai starbucks lemonde",
              "strawberry coconut drink",
              "strawberry frappuccino blended creme",
              "syrup frappuccino blended creme",
              "vanilla creme",
              "syrup creme",
              "vanilla frappuccino blended coffee",
              "vanilla bean blended creme",
              "vanilla sweet cream cold brew",
              "vanilla sweet cream nitro cold brew"]